trigger: none
pr: none
parameters:
  - name: VERSION
    type: string
pool:
  name: 'dds-concourse-ubuntu2004-01'
  workspace:
    clean: all
extends:
  template: pipelines/backend/monorepo-cd.yaml
  parameters:
    appId: concourse-raid-svc
    appVersion: ${{ parameters.VERSION }}
    agentPool: 'dds-concourse-ubuntu2004-01'